setwd("C:/Users/zihao.zhang/Desktop")
simulated = read.csv("ProjectSimulatedData.csv")
summary(simulated)
names(simulated)
lm1 = lm(Y ~ Totalcategory+ TV_copy1  + facebook_copy1 + facebook_copy2, data = simulated)
summary(lm1)
apply(simulated[,c(names(simulated) %in% names(coef(lm1)))], 2, sum, na.rm=T) * coef(lm1)[-1] /sum(simulated$Y,na.rm=T)
hist(simulated$TV_copy1)
summary(simulated$TV_copy1)
